name: Android Debug Build (Capacitor)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
      JAVA_VERSION: 17

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

    - name: Install dependencies
  shell: bash
  run: |
    echo "Working dir: repo root"
    ls -la

    # 如果有 lockfile 使用 npm ci，否则用 npm install
    if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
      echo "Using npm ci"
      npm ci
    else
      echo "No lockfile - using npm install"
      npm install
    fi
    
        
    
  

     
      - name: Build web (vite)
        run: npm run build

      - name: Install Capacitor CLI
        run: npm install @capacitor/cli --no-save

      - name: Setup Android SDK (cmdline tools + platform-tools)
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          components: platform-tools,build-tools;33.0.0
          ndk: false

      - name: Capacitor init (if needed) and add android
        run: |
          APP_ID=com.example.mykanjiapp
          APP_NAME="MyKanjiApp"
          npx cap init "$APP_NAME" "$APP_ID" --web-dir=dist || true
          npx cap add android || true
          npx cap sync android

      - name: Build Android debug APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon -Porg.gradle.jvmargs="-Xmx2048m"

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          
